//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginarDatosFnSQLServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbCursosEntities : DbContext
    {
        public dbCursosEntities()
            : base("name=dbCursosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        [DbFunction("dbCursosEntities", "fnPaginar")]
        public virtual IQueryable<fnPaginar_Result> fnPaginar(Nullable<int> pagina, Nullable<int> cantidadReg)
        {
            var paginaParameter = pagina.HasValue ?
                new ObjectParameter("pagina", pagina) :
                new ObjectParameter("pagina", typeof(int));
    
            var cantidadRegParameter = cantidadReg.HasValue ?
                new ObjectParameter("cantidadReg", cantidadReg) :
                new ObjectParameter("cantidadReg", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnPaginar_Result>("[dbCursosEntities].[fnPaginar](@pagina, @cantidadReg)", paginaParameter, cantidadRegParameter);
        }
    }
}
